apiVersion: v1
kind: Service
metadata:
  name: plan-stock-service
spec:
  type: NodePort
  selector:
    app: plan-stock-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432